services:
  - type: web
    name: next-react-express-app
    env: node
    plan: free
    branch: main

    buildCommand: |
      yarn install
      yarn build

    startCommand: |
      yarn start

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000   # Render assigns a PORT, Express should listen on it
